### ISSUE TITLE
Errors (SQLite missing?) when following tutorial to install "popphp-tutorial"

### ISSUE THREAD

**Issue by lagraviereScience** [popphp/popphp-tutorial#2]
Hey,

I followed those instructions
```
$ composer create-project popphp/popphp-tutorial project-folder
$ cd project-folder
$ ./kettle serve
```

When I do that I get this output:
```
$ ./kettle serve

    Pop Kettle
    ==========

    PHP web server running on the folder public at localhost:8000... (Ctrl-C to stop)

[Sun Mar 21 21:31:01 2021] PHP 7.4.3 Development Server (http://localhost:8000) started
```
Which seems normal

Then I try to access http://localhost:8000 and I get a white page (tested on Firefox and Chrome) and the little Kettle server outputs this:
```
[Sun Mar 21 21:32:57 2021] 127.0.0.1:64244 Accepted
[Sun Mar 21 21:32:57 2021] 127.0.0.1:64245 Accepted
[Sun Mar 21 21:32:57 2021] PHP Warning:  Use of undefined constant SQLITE3_OPEN_READWRITE - assumed 'SQLITE3_OPEN_READWRITE' (this will throw an Error in a future version of PHP) in /mnt/d/PROG/DIVERS/tutorialPop/project-folder/vendor/popphp/pop-db/src/Adapter/Sqlite.php on line 108
[Sun Mar 21 21:32:57 2021] PHP Warning:  Use of undefined constant SQLITE3_OPEN_CREATE - assumed 'SQLITE3_OPEN_CREATE' (this will throw an Error in a future version of PHP) in /mnt/d/PROG/DIVERS/tutorialPop/project-folder/vendor/popphp/pop-db/src/Adapter/Sqlite.php on line 108
[Sun Mar 21 21:32:57 2021] PHP Fatal error:  Uncaught Error: Class 'SQLite3' not found in /mnt/d/PROG/DIVERS/tutorialPop/project-folder/vendor/popphp/pop-db/src/Adapter/Sqlite.php:83
Stack trace:
#0 /mnt/d/PROG/DIVERS/tutorialPop/project-folder/vendor/popphp/pop-db/src/Adapter/Sqlite.php(63): Pop\Db\Adapter\Sqlite->connect()
#1 /mnt/d/PROG/DIVERS/tutorialPop/project-folder/vendor/popphp/pop-db/src/Db.php(58): Pop\Db\Adapter\Sqlite->__construct()
#2 [internal function]: Pop\Db\Db::connect()
#3 /mnt/d/PROG/DIVERS/tutorialPop/project-folder/vendor/popphp/pop-utils/src/CallableObject.php(162): call_user_func_array()
#4 /mnt/d/PROG/DIVERS/tutorialPop/project-folder/vendor/popphp/popphp/src/Service/Locator.php(160): Pop\Utils\CallableObject->call()
#5 /mnt/d/PROG/DIVERS/tutorialPop/project-folder/vendor/popphp/popphp/src/Service/Locator.php(389): Pop\Service\Locator->get()
#6 /mnt/d/PROG/DIVERS/tutorialPop/project-folder/app/src/Module.php(40): Pop\Service\Locator->offsetGet()
#7 [internal function]: Tutorial\Module->Tutorial\{closure}()
#8 /mnt/d/PROG/DIVERS in /mnt/d/PROG/DIVERS/tutorialPop/project-folder/vendor/popphp/pop-db/src/Adapter/Sqlite.php on line 83
[Sun Mar 21 21:32:57 2021] 127.0.0.1:64244 [500]: GET / - Uncaught Error: Class 'SQLite3' not found in /mnt/d/PROG/DIVERS/tutorialPop/project-folder/vendor/popphp/pop-db/src/Adapter/Sqlite.php:83
Stack trace:
#0 /mnt/d/PROG/DIVERS/tutorialPop/project-folder/vendor/popphp/pop-db/src/Adapter/Sqlite.php(63): Pop\Db\Adapter\Sqlite->connect()
#1 /mnt/d/PROG/DIVERS/tutorialPop/project-folder/vendor/popphp/pop-db/src/Db.php(58): Pop\Db\Adapter\Sqlite->__construct()
#2 [internal function]: Pop\Db\Db::connect()
#3 /mnt/d/PROG/DIVERS/tutorialPop/project-folder/vendor/popphp/pop-utils/src/CallableObject.php(162): call_user_func_array()
#4 /mnt/d/PROG/DIVERS/tutorialPop/project-folder/vendor/popphp/popphp/src/Service/Locator.php(160): Pop\Utils\CallableObject->call()
#5 /mnt/d/PROG/DIVERS/tutorialPop/project-folder/vendor/popphp/popphp/src/Service/Locator.php(389): Pop\Service\Locator->get()
#6 /mnt/d/PROG/DIVERS/tutorialPop/project-folder/app/src/Module.php(40): Pop\Service\Locator->offsetGet()
#7 [internal function]: Tutorial\Module->Tutorial\{closure}()
#8 /mnt/d/PROG/DIVERS in /mnt/d/PROG/DIVERS/tutorialPop/project-folder/vendor/popphp/pop-db/src/Adapter/Sqlite.php on line 83
[Sun Mar 21 21:32:57 2021] 127.0.0.1:64244 Closing
[Sun Mar 21 21:32:57 2021] 127.0.0.1:64247 Accepted
```

So I am guessing SQLite is missing
And very probably I did something wrong
Or maybe there's something missing in the scripts or JSON files or in the documentation.

So I am guessing this is an issue with the app and/or its documentation.

**Comment by nicksagona** [comment]
Yes, the errors show that you do not have the SQLite3 extension installed. You should be able to install that and the errors should go away. Or if you have PDO Sqlite installed instead, you could switch to that adapter in the `/app/config/app.web.php` and `/app/config/app.console.php` files. To do that, you would change:

```php
        'database' => [
            'call'   => 'Pop\Db\Db::connect',
            'params' => [
                'adapter' => 'Sqlite',
                'options' => [
                    'database' => __DIR__ . '/../../database/.htpoptutorial.sqlite'
                ]
            ]
        ]
```
to this:

```php
        'database' => [
            'call'   => 'Pop\Db\Db::connect',
            'params' => [
                'adapter' => 'Pdo',
                'options' => [
                    'type'         => 'sqlite',
                    'database' => __DIR__ . '/../../database/.htpoptutorial.sqlite'
                ]
            ]
        ]

```

**Comment by lagraviereScience** [comment]
Thanks so much for the reply!
I am gonna apply the solution you provided and tell you the results ASAP.

Also, I am not sure it is clearly indicated in the documentation that sqlite extension or PDO Sqlite should be installed as prerequisite(?) so that "popphp-tutorial" application works.
